### ISSUE TITLE
README.MD dumpMongoDatabase.ps1 is never defined

### ISSUE THREAD

**Issue by PandahutMushy** [pferreirafabricio/backup-mongo-db#2]
`4.2. Edit the [createSystemScheduledTask.ps1](https://github.com/pferreirafabricio/powerShell-dumpMongoDB/blob/main/createSystemScheduledTask.ps1) script, modifing the variable with the path of the dumpMongoDatabase.ps1 script and the time that the task will run`

What is the "dumpMongoDatabase.ps1" script? It is never referenced anywhere else.

Thanks

**Comment by pferreirafabricio** [comment]
Hi @PandahutMushy! Thank you so much for pointing this out, I overlooked this mistake.

In the commit c68c704 I changed the name of the script but forgot to update the 4.2 item of the README.

Thanks for your contribution.
